// <auto-generated />
namespace RentAMovie.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddStock_Available : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddStock_Available));
        
        string IMigrationMetadata.Id
        {
            get { return "201905060650069_AddStock_Available"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
